### ISSUE TITLE
one question about the dataset

### ISSUE THREAD

**Issue by fjzpcmj** [deep-voxel/automatic_pulmonary_lobe_segmentation_using_deep_learning#1]
hi，it‘s very kind of you to publish your dataset. Currently, i want to make some expriments in your dataset. Can you tell me which 10 scans is used for testing in your dataset?

**Comment by chupengrocky** [comment]
Hi, The following 10 ids are using for testing and the rest are using for training. 

1.3.6.1.4.1.14519.5.2.1.6279.6001.317087518531899043292346860596
1.3.6.1.4.1.14519.5.2.1.6279.6001.193964947698259739624715468431
1.3.6.1.4.1.14519.5.2.1.6279.6001.842980983137518332429408284002
1.3.6.1.4.1.14519.5.2.1.6279.6001.297251044869095073091780740645
1.3.6.1.4.1.14519.5.2.1.6279.6001.281967919138248195763602360723
1.3.6.1.4.1.14519.5.2.1.6279.6001.332453873575389860371315979768
1.3.6.1.4.1.14519.5.2.1.6279.6001.333145094436144085379032922488
1.3.6.1.4.1.14519.5.2.1.6279.6001.199069398344356765037879821616
1.3.6.1.4.1.14519.5.2.1.6279.6001.112740418331256326754121315800
1.3.6.1.4.1.14519.5.2.1.6279.6001.503980049263254396021509831276

**Comment by fjzpcmj** [comment]
@chupengrocky Thanks very much
